name: CI/CD

on:
  push:
    branches: [ master ]
    paths:
        - 'L6/CI-CD/**'
  pull_request:
    branches: [ master ]
    paths:
        - 'L6/CI-CD/**'

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: L6/CI-CD
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 21

      - name: Cache Gradle wrapper and dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('L6/CI-CD/**/*.gradle*', 'L6/CI-CD/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Static analysis (Checkstyle)
        run: ./gradlew checkstyleMain checkstyleTest

      - name: Build JAR
        run: ./gradlew clean build

      - name: Archive JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: project-jar
          path: L6/CI-CD/build/libs/*.jar
